### ISSUE TITLE
No such file or directory: 'src/files/tor.zip' = Error, failed to import core modules.

### ISSUE THREAD

**Issue by Egida** [Nexuzzzz/Cerberus#4]
```
Reading state information... Done
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    main()
  File "setup.py", line 32, in main
    os.remove(os.path.join(tor_path))
FileNotFoundError: [Errno 2] No such file or directory: 'src/files/tor.zip'
root@vpsi1ox7:~/Cerberus# python3 main.py --help

 - Error, failed to import core modules.
 - Stacktrace: 
unsupported operand type(s) for |: 'type' and 'type'
root@vpsi1ox7:~/Cerberus# 
```
Hello, how to fix this error?

**Comment by Nexuzzzz** [comment]
Hmm, i'll look into it tomorrow since its a bit late over here and i am pretty tired. Thanks for reporting the problem!

**Comment by Nexuzzzz** [comment]
While i did fix the problem with the setup script, i was unable to reproduce the second one, i'll implement a debug mode which will show the full stacktrace in a min

**Comment by Nexuzzzz** [comment]
Could you try again?

**Comment by Egida** [comment]
> Could you try again?
```

root@vpsi1ox7:~/Cerberus# python3 main.py --help
 - Error, failed to import core modules.
 - Stacktrace:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    from src.utils import * # import all utilities
  File "/root/Cerberus/src/utils.py", line 71, in <module>
    class utils():
  File "/root/Cerberus/src/utils.py", line 182, in utils
    def get_proxy(self, is_requests=True, force_give=False) -> dict | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
root@vpsi1ox7:~/Cerberus# 
root@vpsi1ox7:~/Cerberus# python3 main.py --help

 - Error, failed to import core modules.
 - Stacktrace:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    from src.utils import * # import all utilities
  File "/root/Cerberus/src/utils.py", line 71, in <module>
    class utils():
  File "/root/Cerberus/src/utils.py", line 182, in utils
    def get_proxy(self, is_requests=True, force_give=False) -> dict | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
root@vpsi1ox7:~/Cerberus# 
```

**Comment by Nexuzzzz** [comment]
hmm, what version of python are you running? I am unable to reproduce this issue

**Comment by Nexuzzzz** [comment]
could you try again now?

**Comment by Egida** [comment]
> hmm, what version of python are you running? I am unable to reproduce this issue

`root@vpsi1ox7:~/Cerberus# python -V
Python 3.9.13`



> could you try again now?

r```
oot@vpsi1ox7:~/Cerberus# python3 main.py --help

 - Error, failed to import core modules.
 - Stacktrace:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    from src.utils import * # import all utilities
  File "/root/Cerberus/src/utils.py", line 71, in <module>
    class utils():
  File "/root/Cerberus/src/utils.py", line 408, in utils
    def buildheaders(self, url, if_socket=False) -> dict | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by Egida** [comment]
> could you try again now?

root@vpsi1ox7:~/Cerberus# python3 main.py --help

 - Error, failed to import core modules.
 - Stacktrace:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    from src.utils import * # import all utilities
  File "/root/Cerberus/src/utils.py", line 71, in <module>
    class utils():
  File "/root/Cerberus/src/utils.py", line 408, in utils
    def buildheaders(self, url, if_socket=False) -> dict | str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Nexuzzzz** [comment]
Could you try using python 3.10.4? If that works, its a version issue and atleast i know the source of the problem then

**Comment by Nexuzzzz** [comment]
closing due to inactivity
